# Generated by Django 2.2.4 on 2019-08-27 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.TextField()),
            ],
            options={
                'db_table': 'schedule_archive',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'schedule_teacher',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('duration', models.IntegerField()),
                ('order', models.IntegerField(unique=True)),
                ('is_show', models.BooleanField(default=True)),
                ('teachers', models.ManyToManyField(related_name='majors', to='schedule.Teacher')),
            ],
            options={
                'db_table': 'schedule_major',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('is_show', models.BooleanField(default=True)),
                ('majors', models.ManyToManyField(related_name='classes', through='schedule.Archive', to='schedule.Major')),
            ],
            options={
                'db_table': 'schedule_class',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='archive',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Class'),
        ),
        migrations.AddField(
            model_name='archive',
            name='major_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Major'),
        ),
        migrations.AlterUniqueTogether(
            name='archive',
            unique_together={('class_id', 'major_id')},
        ),
    ]
